import type { SeedPersona } from "@/lib/types";

export const TAG_VOCAB: { softSkills: string[]; interests: string[] } = {
  softSkills: [
    "Storytelling",
    "Empathy",
    "Resilience",
    "Adaptability",
    "Community Building",
    "Active Listening",
    "Mentorship",
    "Coaching",
    "First Principles",
    "Systems Thinking",
    "Rapid Prototyping",
    "Pattern Recognition",
    "Written Communication",
    "Public Speaking",
    "Facilitation",
    "Decisiveness",
    "Delegation",
    "Recruiting",
    "Fundraising",
    "Negotiation",
    "Cold Outreach",
    "Conflict Resolution",
  ],
  interests: [
    "AI",
    "Product Design",
    "Education",
    "Social Impact",
    "Mental Health",
    "Accessibility",
    "Developer Tools",
    "Open Source",
    "Climate",
    "Sustainability",
    "Fintech",
    "Marketplaces",
    "Creator Economy",
    "Hardware",
    "Robotics",
    "Biotech",
    "Space",
    "Gaming",
    "Music",
    "Sports",
    "Fitness",
    "Cooking",
    "Travel",
    "Reading",
  ],
};

export const SEED_PERSONAS: SeedPersona[] = [
  {
    id: "maya",
    name: "Maya R.",
    emoji: "🌻",
    gradient: ["#FFD60A", "#FF9F1C"],
    tagline: "Building an AI tutor for skilled trades",
    softSkills: [
      "Storytelling",
      "Empathy",
      "Resilience",
      "Adaptability",
      "Community Building",
      "Active Listening",
      "Mentorship",
      "Coaching",
      "Fundraising",
    ],
    interests: [
      "AI",
      "Product Design",
      "Education",
      "Social Impact",
      "Mental Health",
      "Accessibility",
      "Reading",
    ],
    intro: {
      who: "Hey! I'm Maya. I taught high school shop class for six years before I fell down the AI rabbit hole, so I still think of myself as a teacher who accidentally became a founder.",
      building:
        "It's an AI tutor for people going into the trades — electricians, welders, HVAC folks. Basically the patient explainer I wish I could have cloned myself into at 2pm on a Friday.",
      lookingFor:
        "Honestly? People who'll tell me the truth. I've got plenty of cheerleaders. I want two or three people I can text when something's on fire.",
    },
    cannedReplies: [
      "hey you! okay I read your intro and we are suspiciously similar. what are you building?",
      "fair warning: I will ask nosy questions about your users. it's a teacher thing, I can't help it.",
      "if you're ever stuck explaining your thing to a normal human, that's my favourite problem. just say the word.",
    ],
  },
  {
    id: "jordan",
    name: "Jordan T.",
    emoji: "⚡",
    gradient: ["#FF8A00", "#FF3D6E"],
    tagline: "Turning newsletters into real communities",
    softSkills: [
      "Storytelling",
      "Community Building",
      "Empathy",
      "Resilience",
      "Public Speaking",
      "Facilitation",
      "Cold Outreach",
    ],
    interests: [
      "Creator Economy",
      "AI",
      "Product Design",
      "Education",
      "Social Impact",
      "Music",
    ],
    intro: {
      who: "I'm Jordan. I ran events at a big creator platform for four years, quit, and now I do the same thing for myself but with significantly worse healthcare.",
      building:
        "A tool that turns a newsletter audience into an actual community. People who know each other's names, not just a list of email addresses.",
      lookingFor:
        "Someone to swap playbooks with. I've run maybe two hundred events and I still learn something every time I watch how another person opens a room.",
    },
    cannedReplies: [
      "heyyy. quick warning, I reply in paragraphs. it's a newsletter thing.",
      "okay real question — what's the last thing you shipped that scared you a little?",
      "if you ever want to test an idea on a live audience, I've got forty people on a call every other Thursday.",
    ],
  },
  {
    id: "priya",
    name: "Priya N.",
    emoji: "🔮",
    gradient: ["#C77DFF", "#FF6FB5"],
    tagline: "AI that notices when founders are burning out",
    softSkills: [
      "Empathy",
      "Storytelling",
      "Resilience",
      "First Principles",
      "Systems Thinking",
      "Pattern Recognition",
      "Written Communication",
    ],
    interests: [
      "AI",
      "Mental Health",
      "Product Design",
      "Education",
      "Accessibility",
      "Fitness",
    ],
    intro: {
      who: "Priya. I was an ML engineer for most of my twenties, then I watched two close friends melt down in the same quarter and it rearranged my priorities.",
      building:
        "A quiet AI check-in for founders. It reads your own signals back to you before you become the last person to notice you're not okay.",
      lookingFor:
        "People building at the weird intersection of AI and actual human feelings. There aren't many of us and I'd like to know all of you.",
    },
    cannedReplies: [
      "hi! I'll be honest, I read your intro twice. the second time was because I liked it.",
      "how are you actually doing? not the LinkedIn version.",
      "I'm deep in eval hell this week but I always have room for a walk-and-talk call.",
    ],
  },
  {
    id: "amara",
    name: "Amara O.",
    emoji: "🌿",
    gradient: ["#9EF01A", "#38B000"],
    tagline: "Carbon capture that fits in a shipping container",
    softSkills: [
      "Resilience",
      "Adaptability",
      "Systems Thinking",
      "First Principles",
      "Rapid Prototyping",
      "Fundraising",
      "Decisiveness",
    ],
    interests: [
      "Climate",
      "Sustainability",
      "Hardware",
      "Social Impact",
      "Robotics",
      "Space",
    ],
    intro: {
      who: "I'm Amara. Grew up in Lagos, studied chemical engineering, spent five years in industrial ops before I got tired of optimising things I didn't believe in.",
      building:
        "Carbon capture that fits inside a shipping container, so it can go where the emissions actually are instead of where the funding is.",
      lookingFor:
        "People who've raised for hard tech. Hardware timelines break every fundraising template I've ever been handed, and I want to hear how others got around that.",
    },
    cannedReplies: [
      "hi! quick one — are you hardware or software? I ask everyone, it's a bias.",
      "I'm in a factory most days so my replies are either instant or three days late. no in-between.",
      "if you want to see something genuinely cool, I've got a video of the unit running. it hums.",
    ],
  },
  {
    id: "lina",
    name: "Lina S.",
    emoji: "🎨",
    gradient: ["#FF7B9C", "#B5179E"],
    tagline: "Design tools that don't shut people out",
    softSkills: [
      "Storytelling",
      "Empathy",
      "Active Listening",
      "Rapid Prototyping",
      "Facilitation",
      "Written Communication",
    ],
    interests: [
      "Product Design",
      "Accessibility",
      "AI",
      "Creator Economy",
      "Music",
      "Reading",
    ],
    intro: {
      who: "Lina. I was a product designer at three startups and got progressively angrier about how much software just assumes everyone sees and clicks the same way.",
      building:
        "A design tool that flags accessibility problems while you're still sketching, not six months later when someone finally files a complaint.",
      lookingFor:
        "People to sit and critique with. I miss having a desk neighbour who'd lean over and say 'that's not working' before I'd spent a week on it.",
    },
    cannedReplies: [
      "hi! I already looked at your profile twice. the gradient is doing a lot of work, I respect it.",
      "genuine question: who's the one user you're building for? like the actual person.",
      "happy to do a free teardown of whatever you're making. I find it relaxing, which is probably a red flag.",
    ],
  },
  {
    id: "devon",
    name: "Devon K.",
    emoji: "🔧",
    gradient: ["#FFB627", "#E85D04"],
    tagline: "Making APIs debug themselves",
    softSkills: [
      "First Principles",
      "Systems Thinking",
      "Rapid Prototyping",
      "Written Communication",
      "Decisiveness",
      "Mentorship",
    ],
    interests: [
      "Developer Tools",
      "Open Source",
      "AI",
      "Gaming",
      "Robotics",
      "Space",
    ],
    intro: {
      who: "Devon. Backend engineer for nine years, solo for the last one. I'm the person who reads the changelog for fun.",
      building:
        "A tool that watches your API traffic and tells you what broke before your customers do. Very unglamorous. Extremely useful.",
      lookingFor:
        "Other people who like building things properly. And maybe someone who can teach me to talk about my work without sounding like a man page.",
    },
    cannedReplies: [
      "hey. saw you're building something too — what's your stack?",
      "fair warning, I'll probably offer to look at your code. it's how I say hello.",
      "I open sourced half of this last month if you ever want a poke around.",
    ],
  },
  {
    id: "kwame",
    name: "Kwame A.",
    emoji: "🧬",
    gradient: ["#2EC4B6", "#0FA3B1"],
    tagline: "At-home diagnostics for chronic conditions",
    softSkills: [
      "Empathy",
      "Resilience",
      "Systems Thinking",
      "Pattern Recognition",
      "Delegation",
      "Conflict Resolution",
    ],
    interests: [
      "Biotech",
      "Mental Health",
      "Fitness",
      "Climate",
      "Sustainability",
      "Cooking",
    ],
    intro: {
      who: "Kwame. I trained as a clinician, then spent four years in a lab, and now I'm somewhere in between with a company attached to me.",
      building:
        "At-home diagnostics for chronic conditions, so people stop finding out too late just because the clinic was two buses away.",
      lookingFor:
        "People who've built in regulated spaces and survived it. And frankly, someone to talk to who isn't also a scientist.",
    },
    cannedReplies: [
      "hello! I'm slow to reply but I do read everything properly. occupational habit.",
      "what's the hardest constraint you're working under right now? I collect those.",
      "if you're ever in a room with a regulator and quietly panicking, call me. I've done it twice.",
    ],
  },
  {
    id: "theo",
    name: "Theo B.",
    emoji: "💸",
    gradient: ["#4CC9F0", "#4361EE"],
    tagline: "Payment rails for people the banks skipped",
    softSkills: [
      "Negotiation",
      "Fundraising",
      "Cold Outreach",
      "Recruiting",
      "Decisiveness",
      "Public Speaking",
    ],
    interests: [
      "Fintech",
      "Marketplaces",
      "AI",
      "Social Impact",
      "Sports",
      "Travel",
    ],
    intro: {
      who: "Theo here. Ten years in payments, two of them at a bank I will not name, and I got very tired of hearing 'that customer isn't profitable'.",
      building:
        "Payment rails for small merchants who can't get a normal account. Market traders, mobile barbers, that whole economy.",
      lookingFor:
        "Intros, mostly. I'm shameless about it. But also anyone who's negotiated a partnership with an institution ten thousand times their size.",
    },
    cannedReplies: [
      "hey! straight to it — who was your first customer and how did you find them?",
      "I'm probably going to ask you for an intro at some point. I'll ask nicely.",
      "if you ever need someone to read a contract with fresh eyes, send it over. it's weirdly my happy place.",
    ],
  },
  {
    id: "sana",
    name: "Sana M.",
    emoji: "🎮",
    gradient: ["#F72585", "#7209B7"],
    tagline: "Game controllers built for one-handed play",
    softSkills: [
      "Resilience",
      "Rapid Prototyping",
      "Pattern Recognition",
      "Decisiveness",
      "Delegation",
      "Coaching",
    ],
    interests: [
      "Gaming",
      "Hardware",
      "Accessibility",
      "Robotics",
      "Music",
      "Sports",
    ],
    intro: {
      who: "Sana. Competitive gamer until my wrist gave out, then I got into hardware because I refused to stop playing.",
      building:
        "Game controllers you can use one-handed. Started as a thing for me, turned out a lot of people needed it and nobody was making it.",
      lookingFor:
        "Manufacturing people, badly. And playtesters — I will genuinely mail you a prototype if you ask.",
    },
    cannedReplies: [
      "yo. do you play anything? I need to know what I'm working with here.",
      "I've got a stack of prototypes on my desk and one of them can be yours.",
      "warning: I make decisions fast and change my mind faster. speedrun brain.",
    ],
  },
  {
    id: "milo",
    name: "Milo C.",
    emoji: "🍜",
    gradient: ["#FFD166", "#EF476F"],
    tagline: "Renting out restaurant kitchens in their dead hours",
    softSkills: [
      "Adaptability",
      "Negotiation",
      "Cold Outreach",
      "Recruiting",
      "Facilitation",
      "Conflict Resolution",
    ],
    interests: [
      "Cooking",
      "Marketplaces",
      "Travel",
      "Sports",
      "Fitness",
      "Music",
    ],
    intro: {
      who: "Milo. I cooked professionally for eight years, burned out spectacularly, and now I build things for the people still in the kitchen.",
      building:
        "A marketplace that rents out restaurant kitchens during their dead hours to people starting food businesses out of their homes.",
      lookingFor:
        "Anyone who's done two-sided marketplaces. Also, honestly, friends. Restaurant hours wrecked my social life and I'm rebuilding it.",
    },
    cannedReplies: [
      "hey! first thing I ask anyone: what's the best thing you've eaten this week?",
      "I'm free before 11am and after 10pm. that's kitchen brain, sorry.",
      "if you're ever in town I'll cook for you. that's not a figure of speech.",
    ],
  },
];
